//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Controle_Acesso.Models
{
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class ACESSO
    {
        [Key, Column(Order = 0)]
        public int ID_LOGIN { get; set; }
        public string EMAIL { get; set; }
        public string SENHA { get; set; }
        public string ATIVO { get; set; }
        public string PERFIL { get; set; }
        public string NOME { get; set; }
        public string SOBRENOME { get; set; }
    }
}
